const routes = {
    home: '/',
    aboutus: '/aboutus',
    tour: '/tour',
    tourdetail: 'tour/:id',
    destination: '/destination',
    payment: '/payment/:id',
    blog: '/blog',
    search: '/search',
    profile: '/:nickname',
    admin: '/admin',
    adminDestination: '/admin/destination',
    adminTour: '/admin/tour',
    adminBooking: '/admin/booking',
    adminTraveler: '/admin/traveler',
    adminGuide: '/admin/guide',
    adminGallery: '/admin/gallery',
    adminFeedback: '/admin/feedback',
    adminMessage: '/admin/message',
    signin: '/signin',
    signup: '/signup',
    signout: '/signout',
};

export default routes;
