const routes = {
    home: '/',
    aboutus: '/aboutus',
    tour: '/tour',
    tourdetail: 'tour/:id',
    destination: '/destination',
    payment: '/payment/:id',
    blog: '/blog',
    search: '/search',
    profile: '/profile',
    admin: '/admin',
    adminDestination: '/admin/destination',
    adminAddDestination: '/admin/destination/add',
    adminAddCategory: '/admin/category/add',
    adminEditDestination: '/admin/destination/edit/:id',
    adminEditCategory: '/admin/category/edit/:id',
    adminTour: '/admin/tour',
    adminAddTour: '/admin/tour/add',
    adminEditTour: '/admin/tour/edit/:id',
    adminEditTourPlan: '/admin/tour/tourplan/edit/:id',
    adminBooking: '/admin/booking',
    adminTraveler: '/admin/traveler',
    adminGuide: '/admin/guide',
    adminGallery: '/admin/gallery',
    adminAddGallery: '/admin/gallery/add',
    adminFeedback: '/admin/feedback',
    adminMessage: '/admin/message',
    signin: '/signin',
    signup: '/signup',
    signout: '/signout',
};

export default routes;
